version: "3"
services:
  books:
    container_name: vassallo_giacomo_app
    build: .
    command: nodemon --watch . -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www
    links:
      - "mongo_books:mongohost"
  mongo_books:
    container_name: vassallo_giacomo_books
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"